apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sky_note
  template:
    metadata:
      labels:
        app: sky_note
    spec:
      containers:
        - name: nuxt-app
          image: gcr.io/kubernetes-practice-293800/sky_note:v1
          ports:
            - containerPort: 3000
          args: ["npm", "run", "dev"]